// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// Endpoint undocumented
type Endpoint struct {
	// Object is the base model of Endpoint
	Object
	// UserAgent undocumented
	UserAgent *UserAgent `json:"userAgent,omitempty"`
}
