// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// ScheduleRequestBuilder is request builder for Schedule
type ScheduleRequestBuilder struct{ BaseRequestBuilder }

// Request returns ScheduleRequest
func (b *ScheduleRequestBuilder) Request() *ScheduleRequest {
	return &ScheduleRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ScheduleRequest is request for Schedule
type ScheduleRequest struct{ BaseRequest }

// Get performs GET request for Schedule
func (r *ScheduleRequest) Get(ctx context.Context) (resObj *Schedule, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Schedule
func (r *ScheduleRequest) Update(ctx context.Context, reqObj *Schedule) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Schedule
func (r *ScheduleRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

// ScheduleChangeRequestRequestBuilder is request builder for ScheduleChangeRequest
type ScheduleChangeRequestRequestBuilder struct{ BaseRequestBuilder }

// Request returns ScheduleChangeRequestRequest
func (b *ScheduleChangeRequestRequestBuilder) Request() *ScheduleChangeRequestRequest {
	return &ScheduleChangeRequestRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ScheduleChangeRequestRequest is request for ScheduleChangeRequest
type ScheduleChangeRequestRequest struct{ BaseRequest }

// Get performs GET request for ScheduleChangeRequest
func (r *ScheduleChangeRequestRequest) Get(ctx context.Context) (resObj *ScheduleChangeRequest, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ScheduleChangeRequest
func (r *ScheduleChangeRequestRequest) Update(ctx context.Context, reqObj *ScheduleChangeRequest) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ScheduleChangeRequest
func (r *ScheduleChangeRequestRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
