// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// ServiceAnnouncement is navigation property
func (b *AdminRequestBuilder) ServiceAnnouncement() *ServiceAnnouncementRequestBuilder {
	bb := &ServiceAnnouncementRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/serviceAnnouncement"
	return bb
}

// Windows is navigation property
func (b *AdminRequestBuilder) Windows() *WindowsRequestBuilder {
	bb := &WindowsRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/windows"
	return bb
}
