// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// SourceCollection is navigation property
func (b *EstimateStatisticsOperationRequestBuilder) SourceCollection() *SourceCollectionRequestBuilder {
	bb := &SourceCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/sourceCollection"
	return bb
}
