// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// FromTerm is navigation property
func (b *RelationRequestBuilder) FromTerm() *TermRequestBuilder {
	bb := &TermRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/fromTerm"
	return bb
}

// Set is navigation property
func (b *RelationRequestBuilder) Set() *SetRequestBuilder {
	bb := &SetRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/set"
	return bb
}

// ToTerm is navigation property
func (b *RelationRequestBuilder) ToTerm() *TermRequestBuilder {
	bb := &TermRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/toTerm"
	return bb
}
