// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// ChangeTrackedEntityStageForDeletionRequestParameter undocumented
type ChangeTrackedEntityStageForDeletionRequestParameter struct {
}
