// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// ChildSelectability undocumented
type ChildSelectability string

const (
	// ChildSelectabilityVOne undocumented
	ChildSelectabilityVOne ChildSelectability = "One"
	// ChildSelectabilityVMany undocumented
	ChildSelectabilityVMany ChildSelectability = "Many"
)

var (
	// ChildSelectabilityPOne is a pointer to ChildSelectabilityVOne
	ChildSelectabilityPOne = &_ChildSelectabilityPOne
	// ChildSelectabilityPMany is a pointer to ChildSelectabilityVMany
	ChildSelectabilityPMany = &_ChildSelectabilityPMany
)

var (
	_ChildSelectabilityPOne  = ChildSelectabilityVOne
	_ChildSelectabilityPMany = ChildSelectabilityVMany
)
