// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// ScheduledRetireState undocumented
type ScheduledRetireState string

const (
	// ScheduledRetireStateVCancelRetire undocumented
	ScheduledRetireStateVCancelRetire ScheduledRetireState = "cancelRetire"
	// ScheduledRetireStateVComfirmRetire undocumented
	ScheduledRetireStateVComfirmRetire ScheduledRetireState = "comfirmRetire"
)

var (
	// ScheduledRetireStatePCancelRetire is a pointer to ScheduledRetireStateVCancelRetire
	ScheduledRetireStatePCancelRetire = &_ScheduledRetireStatePCancelRetire
	// ScheduledRetireStatePComfirmRetire is a pointer to ScheduledRetireStateVComfirmRetire
	ScheduledRetireStatePComfirmRetire = &_ScheduledRetireStatePComfirmRetire
)

var (
	_ScheduledRetireStatePCancelRetire  = ScheduledRetireStateVCancelRetire
	_ScheduledRetireStatePComfirmRetire = ScheduledRetireStateVComfirmRetire
)
