// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// NetworkConnectionType undocumented
type NetworkConnectionType string

const (
	// NetworkConnectionTypeVUnknown undocumented
	NetworkConnectionTypeVUnknown NetworkConnectionType = "unknown"
	// NetworkConnectionTypeVWired undocumented
	NetworkConnectionTypeVWired NetworkConnectionType = "wired"
	// NetworkConnectionTypeVWiFi undocumented
	NetworkConnectionTypeVWiFi NetworkConnectionType = "wifi"
	// NetworkConnectionTypeVMobile undocumented
	NetworkConnectionTypeVMobile NetworkConnectionType = "mobile"
	// NetworkConnectionTypeVTunnel undocumented
	NetworkConnectionTypeVTunnel NetworkConnectionType = "tunnel"
	// NetworkConnectionTypeVUnknownFutureValue undocumented
	NetworkConnectionTypeVUnknownFutureValue NetworkConnectionType = "unknownFutureValue"
)

var (
	// NetworkConnectionTypePUnknown is a pointer to NetworkConnectionTypeVUnknown
	NetworkConnectionTypePUnknown = &_NetworkConnectionTypePUnknown
	// NetworkConnectionTypePWired is a pointer to NetworkConnectionTypeVWired
	NetworkConnectionTypePWired = &_NetworkConnectionTypePWired
	// NetworkConnectionTypePWiFi is a pointer to NetworkConnectionTypeVWiFi
	NetworkConnectionTypePWiFi = &_NetworkConnectionTypePWiFi
	// NetworkConnectionTypePMobile is a pointer to NetworkConnectionTypeVMobile
	NetworkConnectionTypePMobile = &_NetworkConnectionTypePMobile
	// NetworkConnectionTypePTunnel is a pointer to NetworkConnectionTypeVTunnel
	NetworkConnectionTypePTunnel = &_NetworkConnectionTypePTunnel
	// NetworkConnectionTypePUnknownFutureValue is a pointer to NetworkConnectionTypeVUnknownFutureValue
	NetworkConnectionTypePUnknownFutureValue = &_NetworkConnectionTypePUnknownFutureValue
)

var (
	_NetworkConnectionTypePUnknown            = NetworkConnectionTypeVUnknown
	_NetworkConnectionTypePWired              = NetworkConnectionTypeVWired
	_NetworkConnectionTypePWiFi               = NetworkConnectionTypeVWiFi
	_NetworkConnectionTypePMobile             = NetworkConnectionTypeVMobile
	_NetworkConnectionTypePTunnel             = NetworkConnectionTypeVTunnel
	_NetworkConnectionTypePUnknownFutureValue = NetworkConnectionTypeVUnknownFutureValue
)

// NetworkSingleSignOnType undocumented
type NetworkSingleSignOnType string

const (
	// NetworkSingleSignOnTypeVDisabled undocumented
	NetworkSingleSignOnTypeVDisabled NetworkSingleSignOnType = "disabled"
	// NetworkSingleSignOnTypeVPrelogon undocumented
	NetworkSingleSignOnTypeVPrelogon NetworkSingleSignOnType = "prelogon"
	// NetworkSingleSignOnTypeVPostlogon undocumented
	NetworkSingleSignOnTypeVPostlogon NetworkSingleSignOnType = "postlogon"
)

var (
	// NetworkSingleSignOnTypePDisabled is a pointer to NetworkSingleSignOnTypeVDisabled
	NetworkSingleSignOnTypePDisabled = &_NetworkSingleSignOnTypePDisabled
	// NetworkSingleSignOnTypePPrelogon is a pointer to NetworkSingleSignOnTypeVPrelogon
	NetworkSingleSignOnTypePPrelogon = &_NetworkSingleSignOnTypePPrelogon
	// NetworkSingleSignOnTypePPostlogon is a pointer to NetworkSingleSignOnTypeVPostlogon
	NetworkSingleSignOnTypePPostlogon = &_NetworkSingleSignOnTypePPostlogon
)

var (
	_NetworkSingleSignOnTypePDisabled  = NetworkSingleSignOnTypeVDisabled
	_NetworkSingleSignOnTypePPrelogon  = NetworkSingleSignOnTypeVPrelogon
	_NetworkSingleSignOnTypePPostlogon = NetworkSingleSignOnTypeVPostlogon
)

// NetworkType undocumented
type NetworkType string

const (
	// NetworkTypeVIntranet undocumented
	NetworkTypeVIntranet NetworkType = "intranet"
	// NetworkTypeVExtranet undocumented
	NetworkTypeVExtranet NetworkType = "extranet"
	// NetworkTypeVNamedNetwork undocumented
	NetworkTypeVNamedNetwork NetworkType = "namedNetwork"
	// NetworkTypeVTrusted undocumented
	NetworkTypeVTrusted NetworkType = "trusted"
	// NetworkTypeVUnknownFutureValue undocumented
	NetworkTypeVUnknownFutureValue NetworkType = "unknownFutureValue"
	// NetworkTypeVTrustedNamedLocation undocumented
	NetworkTypeVTrustedNamedLocation NetworkType = "trustedNamedLocation"
)

var (
	// NetworkTypePIntranet is a pointer to NetworkTypeVIntranet
	NetworkTypePIntranet = &_NetworkTypePIntranet
	// NetworkTypePExtranet is a pointer to NetworkTypeVExtranet
	NetworkTypePExtranet = &_NetworkTypePExtranet
	// NetworkTypePNamedNetwork is a pointer to NetworkTypeVNamedNetwork
	NetworkTypePNamedNetwork = &_NetworkTypePNamedNetwork
	// NetworkTypePTrusted is a pointer to NetworkTypeVTrusted
	NetworkTypePTrusted = &_NetworkTypePTrusted
	// NetworkTypePUnknownFutureValue is a pointer to NetworkTypeVUnknownFutureValue
	NetworkTypePUnknownFutureValue = &_NetworkTypePUnknownFutureValue
	// NetworkTypePTrustedNamedLocation is a pointer to NetworkTypeVTrustedNamedLocation
	NetworkTypePTrustedNamedLocation = &_NetworkTypePTrustedNamedLocation
)

var (
	_NetworkTypePIntranet             = NetworkTypeVIntranet
	_NetworkTypePExtranet             = NetworkTypeVExtranet
	_NetworkTypePNamedNetwork         = NetworkTypeVNamedNetwork
	_NetworkTypePTrusted              = NetworkTypeVTrusted
	_NetworkTypePUnknownFutureValue   = NetworkTypeVUnknownFutureValue
	_NetworkTypePTrustedNamedLocation = NetworkTypeVTrustedNamedLocation
)
