// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// EnrollmentAvailabilityOptions undocumented
type EnrollmentAvailabilityOptions string

const (
	// EnrollmentAvailabilityOptionsVAvailableWithPrompts undocumented
	EnrollmentAvailabilityOptionsVAvailableWithPrompts EnrollmentAvailabilityOptions = "availableWithPrompts"
	// EnrollmentAvailabilityOptionsVAvailableWithoutPrompts undocumented
	EnrollmentAvailabilityOptionsVAvailableWithoutPrompts EnrollmentAvailabilityOptions = "availableWithoutPrompts"
	// EnrollmentAvailabilityOptionsVUnavailable undocumented
	EnrollmentAvailabilityOptionsVUnavailable EnrollmentAvailabilityOptions = "unavailable"
)

var (
	// EnrollmentAvailabilityOptionsPAvailableWithPrompts is a pointer to EnrollmentAvailabilityOptionsVAvailableWithPrompts
	EnrollmentAvailabilityOptionsPAvailableWithPrompts = &_EnrollmentAvailabilityOptionsPAvailableWithPrompts
	// EnrollmentAvailabilityOptionsPAvailableWithoutPrompts is a pointer to EnrollmentAvailabilityOptionsVAvailableWithoutPrompts
	EnrollmentAvailabilityOptionsPAvailableWithoutPrompts = &_EnrollmentAvailabilityOptionsPAvailableWithoutPrompts
	// EnrollmentAvailabilityOptionsPUnavailable is a pointer to EnrollmentAvailabilityOptionsVUnavailable
	EnrollmentAvailabilityOptionsPUnavailable = &_EnrollmentAvailabilityOptionsPUnavailable
)

var (
	_EnrollmentAvailabilityOptionsPAvailableWithPrompts    = EnrollmentAvailabilityOptionsVAvailableWithPrompts
	_EnrollmentAvailabilityOptionsPAvailableWithoutPrompts = EnrollmentAvailabilityOptionsVAvailableWithoutPrompts
	_EnrollmentAvailabilityOptionsPUnavailable             = EnrollmentAvailabilityOptionsVUnavailable
)

// EnrollmentState undocumented
type EnrollmentState string

const (
	// EnrollmentStateVUnknown undocumented
	EnrollmentStateVUnknown EnrollmentState = "unknown"
	// EnrollmentStateVEnrolled undocumented
	EnrollmentStateVEnrolled EnrollmentState = "enrolled"
	// EnrollmentStateVPendingReset undocumented
	EnrollmentStateVPendingReset EnrollmentState = "pendingReset"
	// EnrollmentStateVFailed undocumented
	EnrollmentStateVFailed EnrollmentState = "failed"
	// EnrollmentStateVNotContacted undocumented
	EnrollmentStateVNotContacted EnrollmentState = "notContacted"
	// EnrollmentStateVBlocked undocumented
	EnrollmentStateVBlocked EnrollmentState = "blocked"
)

var (
	// EnrollmentStatePUnknown is a pointer to EnrollmentStateVUnknown
	EnrollmentStatePUnknown = &_EnrollmentStatePUnknown
	// EnrollmentStatePEnrolled is a pointer to EnrollmentStateVEnrolled
	EnrollmentStatePEnrolled = &_EnrollmentStatePEnrolled
	// EnrollmentStatePPendingReset is a pointer to EnrollmentStateVPendingReset
	EnrollmentStatePPendingReset = &_EnrollmentStatePPendingReset
	// EnrollmentStatePFailed is a pointer to EnrollmentStateVFailed
	EnrollmentStatePFailed = &_EnrollmentStatePFailed
	// EnrollmentStatePNotContacted is a pointer to EnrollmentStateVNotContacted
	EnrollmentStatePNotContacted = &_EnrollmentStatePNotContacted
	// EnrollmentStatePBlocked is a pointer to EnrollmentStateVBlocked
	EnrollmentStatePBlocked = &_EnrollmentStatePBlocked
)

var (
	_EnrollmentStatePUnknown      = EnrollmentStateVUnknown
	_EnrollmentStatePEnrolled     = EnrollmentStateVEnrolled
	_EnrollmentStatePPendingReset = EnrollmentStateVPendingReset
	_EnrollmentStatePFailed       = EnrollmentStateVFailed
	_EnrollmentStatePNotContacted = EnrollmentStateVNotContacted
	_EnrollmentStatePBlocked      = EnrollmentStateVBlocked
)
