// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// Label undocumented
type Label string

const (
	// LabelVTitle undocumented
	LabelVTitle Label = "title"
	// LabelVURL undocumented
	LabelVURL Label = "url"
	// LabelVCreatedBy undocumented
	LabelVCreatedBy Label = "createdBy"
	// LabelVLastModifiedBy undocumented
	LabelVLastModifiedBy Label = "lastModifiedBy"
	// LabelVAuthors undocumented
	LabelVAuthors Label = "authors"
	// LabelVCreatedDateTime undocumented
	LabelVCreatedDateTime Label = "createdDateTime"
	// LabelVLastModifiedDateTime undocumented
	LabelVLastModifiedDateTime Label = "lastModifiedDateTime"
	// LabelVFileName undocumented
	LabelVFileName Label = "fileName"
	// LabelVFileExtension undocumented
	LabelVFileExtension Label = "fileExtension"
	// LabelVUnknownFutureValue undocumented
	LabelVUnknownFutureValue Label = "unknownFutureValue"
	// LabelVIconURL undocumented
	LabelVIconURL Label = "iconUrl"
	// LabelVContainerName undocumented
	LabelVContainerName Label = "containerName"
	// LabelVContainerURL undocumented
	LabelVContainerURL Label = "containerUrl"
)

var (
	// LabelPTitle is a pointer to LabelVTitle
	LabelPTitle = &_LabelPTitle
	// LabelPURL is a pointer to LabelVURL
	LabelPURL = &_LabelPURL
	// LabelPCreatedBy is a pointer to LabelVCreatedBy
	LabelPCreatedBy = &_LabelPCreatedBy
	// LabelPLastModifiedBy is a pointer to LabelVLastModifiedBy
	LabelPLastModifiedBy = &_LabelPLastModifiedBy
	// LabelPAuthors is a pointer to LabelVAuthors
	LabelPAuthors = &_LabelPAuthors
	// LabelPCreatedDateTime is a pointer to LabelVCreatedDateTime
	LabelPCreatedDateTime = &_LabelPCreatedDateTime
	// LabelPLastModifiedDateTime is a pointer to LabelVLastModifiedDateTime
	LabelPLastModifiedDateTime = &_LabelPLastModifiedDateTime
	// LabelPFileName is a pointer to LabelVFileName
	LabelPFileName = &_LabelPFileName
	// LabelPFileExtension is a pointer to LabelVFileExtension
	LabelPFileExtension = &_LabelPFileExtension
	// LabelPUnknownFutureValue is a pointer to LabelVUnknownFutureValue
	LabelPUnknownFutureValue = &_LabelPUnknownFutureValue
	// LabelPIconURL is a pointer to LabelVIconURL
	LabelPIconURL = &_LabelPIconURL
	// LabelPContainerName is a pointer to LabelVContainerName
	LabelPContainerName = &_LabelPContainerName
	// LabelPContainerURL is a pointer to LabelVContainerURL
	LabelPContainerURL = &_LabelPContainerURL
)

var (
	_LabelPTitle                = LabelVTitle
	_LabelPURL                  = LabelVURL
	_LabelPCreatedBy            = LabelVCreatedBy
	_LabelPLastModifiedBy       = LabelVLastModifiedBy
	_LabelPAuthors              = LabelVAuthors
	_LabelPCreatedDateTime      = LabelVCreatedDateTime
	_LabelPLastModifiedDateTime = LabelVLastModifiedDateTime
	_LabelPFileName             = LabelVFileName
	_LabelPFileExtension        = LabelVFileExtension
	_LabelPUnknownFutureValue   = LabelVUnknownFutureValue
	_LabelPIconURL              = LabelVIconURL
	_LabelPContainerName        = LabelVContainerName
	_LabelPContainerURL         = LabelVContainerURL
)
