// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// AuthenticationMethodFeature undocumented
type AuthenticationMethodFeature string

const (
	// AuthenticationMethodFeatureVSsprRegistered undocumented
	AuthenticationMethodFeatureVSsprRegistered AuthenticationMethodFeature = "ssprRegistered"
	// AuthenticationMethodFeatureVSsprEnabled undocumented
	AuthenticationMethodFeatureVSsprEnabled AuthenticationMethodFeature = "ssprEnabled"
	// AuthenticationMethodFeatureVSsprCapable undocumented
	AuthenticationMethodFeatureVSsprCapable AuthenticationMethodFeature = "ssprCapable"
	// AuthenticationMethodFeatureVPasswordlessCapable undocumented
	AuthenticationMethodFeatureVPasswordlessCapable AuthenticationMethodFeature = "passwordlessCapable"
	// AuthenticationMethodFeatureVMFACapable undocumented
	AuthenticationMethodFeatureVMFACapable AuthenticationMethodFeature = "mfaCapable"
)

var (
	// AuthenticationMethodFeaturePSsprRegistered is a pointer to AuthenticationMethodFeatureVSsprRegistered
	AuthenticationMethodFeaturePSsprRegistered = &_AuthenticationMethodFeaturePSsprRegistered
	// AuthenticationMethodFeaturePSsprEnabled is a pointer to AuthenticationMethodFeatureVSsprEnabled
	AuthenticationMethodFeaturePSsprEnabled = &_AuthenticationMethodFeaturePSsprEnabled
	// AuthenticationMethodFeaturePSsprCapable is a pointer to AuthenticationMethodFeatureVSsprCapable
	AuthenticationMethodFeaturePSsprCapable = &_AuthenticationMethodFeaturePSsprCapable
	// AuthenticationMethodFeaturePPasswordlessCapable is a pointer to AuthenticationMethodFeatureVPasswordlessCapable
	AuthenticationMethodFeaturePPasswordlessCapable = &_AuthenticationMethodFeaturePPasswordlessCapable
	// AuthenticationMethodFeaturePMFACapable is a pointer to AuthenticationMethodFeatureVMFACapable
	AuthenticationMethodFeaturePMFACapable = &_AuthenticationMethodFeaturePMFACapable
)

var (
	_AuthenticationMethodFeaturePSsprRegistered      = AuthenticationMethodFeatureVSsprRegistered
	_AuthenticationMethodFeaturePSsprEnabled         = AuthenticationMethodFeatureVSsprEnabled
	_AuthenticationMethodFeaturePSsprCapable         = AuthenticationMethodFeatureVSsprCapable
	_AuthenticationMethodFeaturePPasswordlessCapable = AuthenticationMethodFeatureVPasswordlessCapable
	_AuthenticationMethodFeaturePMFACapable          = AuthenticationMethodFeatureVMFACapable
)

// AuthenticationMethodKeyStrength undocumented
type AuthenticationMethodKeyStrength string

const (
	// AuthenticationMethodKeyStrengthVNormal undocumented
	AuthenticationMethodKeyStrengthVNormal AuthenticationMethodKeyStrength = "normal"
	// AuthenticationMethodKeyStrengthVWeak undocumented
	AuthenticationMethodKeyStrengthVWeak AuthenticationMethodKeyStrength = "weak"
	// AuthenticationMethodKeyStrengthVUnknown undocumented
	AuthenticationMethodKeyStrengthVUnknown AuthenticationMethodKeyStrength = "unknown"
)

var (
	// AuthenticationMethodKeyStrengthPNormal is a pointer to AuthenticationMethodKeyStrengthVNormal
	AuthenticationMethodKeyStrengthPNormal = &_AuthenticationMethodKeyStrengthPNormal
	// AuthenticationMethodKeyStrengthPWeak is a pointer to AuthenticationMethodKeyStrengthVWeak
	AuthenticationMethodKeyStrengthPWeak = &_AuthenticationMethodKeyStrengthPWeak
	// AuthenticationMethodKeyStrengthPUnknown is a pointer to AuthenticationMethodKeyStrengthVUnknown
	AuthenticationMethodKeyStrengthPUnknown = &_AuthenticationMethodKeyStrengthPUnknown
)

var (
	_AuthenticationMethodKeyStrengthPNormal  = AuthenticationMethodKeyStrengthVNormal
	_AuthenticationMethodKeyStrengthPWeak    = AuthenticationMethodKeyStrengthVWeak
	_AuthenticationMethodKeyStrengthPUnknown = AuthenticationMethodKeyStrengthVUnknown
)

// AuthenticationMethodSignInState undocumented
type AuthenticationMethodSignInState string

const (
	// AuthenticationMethodSignInStateVNotSupported undocumented
	AuthenticationMethodSignInStateVNotSupported AuthenticationMethodSignInState = "notSupported"
	// AuthenticationMethodSignInStateVNotAllowedByPolicy undocumented
	AuthenticationMethodSignInStateVNotAllowedByPolicy AuthenticationMethodSignInState = "notAllowedByPolicy"
	// AuthenticationMethodSignInStateVNotEnabled undocumented
	AuthenticationMethodSignInStateVNotEnabled AuthenticationMethodSignInState = "notEnabled"
	// AuthenticationMethodSignInStateVPhoneNumberNotUnique undocumented
	AuthenticationMethodSignInStateVPhoneNumberNotUnique AuthenticationMethodSignInState = "phoneNumberNotUnique"
	// AuthenticationMethodSignInStateVReady undocumented
	AuthenticationMethodSignInStateVReady AuthenticationMethodSignInState = "ready"
	// AuthenticationMethodSignInStateVNotConfigured undocumented
	AuthenticationMethodSignInStateVNotConfigured AuthenticationMethodSignInState = "notConfigured"
	// AuthenticationMethodSignInStateVUnknownFutureValue undocumented
	AuthenticationMethodSignInStateVUnknownFutureValue AuthenticationMethodSignInState = "unknownFutureValue"
)

var (
	// AuthenticationMethodSignInStatePNotSupported is a pointer to AuthenticationMethodSignInStateVNotSupported
	AuthenticationMethodSignInStatePNotSupported = &_AuthenticationMethodSignInStatePNotSupported
	// AuthenticationMethodSignInStatePNotAllowedByPolicy is a pointer to AuthenticationMethodSignInStateVNotAllowedByPolicy
	AuthenticationMethodSignInStatePNotAllowedByPolicy = &_AuthenticationMethodSignInStatePNotAllowedByPolicy
	// AuthenticationMethodSignInStatePNotEnabled is a pointer to AuthenticationMethodSignInStateVNotEnabled
	AuthenticationMethodSignInStatePNotEnabled = &_AuthenticationMethodSignInStatePNotEnabled
	// AuthenticationMethodSignInStatePPhoneNumberNotUnique is a pointer to AuthenticationMethodSignInStateVPhoneNumberNotUnique
	AuthenticationMethodSignInStatePPhoneNumberNotUnique = &_AuthenticationMethodSignInStatePPhoneNumberNotUnique
	// AuthenticationMethodSignInStatePReady is a pointer to AuthenticationMethodSignInStateVReady
	AuthenticationMethodSignInStatePReady = &_AuthenticationMethodSignInStatePReady
	// AuthenticationMethodSignInStatePNotConfigured is a pointer to AuthenticationMethodSignInStateVNotConfigured
	AuthenticationMethodSignInStatePNotConfigured = &_AuthenticationMethodSignInStatePNotConfigured
	// AuthenticationMethodSignInStatePUnknownFutureValue is a pointer to AuthenticationMethodSignInStateVUnknownFutureValue
	AuthenticationMethodSignInStatePUnknownFutureValue = &_AuthenticationMethodSignInStatePUnknownFutureValue
)

var (
	_AuthenticationMethodSignInStatePNotSupported         = AuthenticationMethodSignInStateVNotSupported
	_AuthenticationMethodSignInStatePNotAllowedByPolicy   = AuthenticationMethodSignInStateVNotAllowedByPolicy
	_AuthenticationMethodSignInStatePNotEnabled           = AuthenticationMethodSignInStateVNotEnabled
	_AuthenticationMethodSignInStatePPhoneNumberNotUnique = AuthenticationMethodSignInStateVPhoneNumberNotUnique
	_AuthenticationMethodSignInStatePReady                = AuthenticationMethodSignInStateVReady
	_AuthenticationMethodSignInStatePNotConfigured        = AuthenticationMethodSignInStateVNotConfigured
	_AuthenticationMethodSignInStatePUnknownFutureValue   = AuthenticationMethodSignInStateVUnknownFutureValue
)

// AuthenticationMethodState undocumented
type AuthenticationMethodState string

const (
	// AuthenticationMethodStateVEnabled undocumented
	AuthenticationMethodStateVEnabled AuthenticationMethodState = "enabled"
	// AuthenticationMethodStateVDisabled undocumented
	AuthenticationMethodStateVDisabled AuthenticationMethodState = "disabled"
)

var (
	// AuthenticationMethodStatePEnabled is a pointer to AuthenticationMethodStateVEnabled
	AuthenticationMethodStatePEnabled = &_AuthenticationMethodStatePEnabled
	// AuthenticationMethodStatePDisabled is a pointer to AuthenticationMethodStateVDisabled
	AuthenticationMethodStatePDisabled = &_AuthenticationMethodStatePDisabled
)

var (
	_AuthenticationMethodStatePEnabled  = AuthenticationMethodStateVEnabled
	_AuthenticationMethodStatePDisabled = AuthenticationMethodStateVDisabled
)

// AuthenticationMethodTargetType undocumented
type AuthenticationMethodTargetType string

const (
	// AuthenticationMethodTargetTypeVUser undocumented
	AuthenticationMethodTargetTypeVUser AuthenticationMethodTargetType = "user"
	// AuthenticationMethodTargetTypeVGroup undocumented
	AuthenticationMethodTargetTypeVGroup AuthenticationMethodTargetType = "group"
	// AuthenticationMethodTargetTypeVUnknownFutureValue undocumented
	AuthenticationMethodTargetTypeVUnknownFutureValue AuthenticationMethodTargetType = "unknownFutureValue"
)

var (
	// AuthenticationMethodTargetTypePUser is a pointer to AuthenticationMethodTargetTypeVUser
	AuthenticationMethodTargetTypePUser = &_AuthenticationMethodTargetTypePUser
	// AuthenticationMethodTargetTypePGroup is a pointer to AuthenticationMethodTargetTypeVGroup
	AuthenticationMethodTargetTypePGroup = &_AuthenticationMethodTargetTypePGroup
	// AuthenticationMethodTargetTypePUnknownFutureValue is a pointer to AuthenticationMethodTargetTypeVUnknownFutureValue
	AuthenticationMethodTargetTypePUnknownFutureValue = &_AuthenticationMethodTargetTypePUnknownFutureValue
)

var (
	_AuthenticationMethodTargetTypePUser               = AuthenticationMethodTargetTypeVUser
	_AuthenticationMethodTargetTypePGroup              = AuthenticationMethodTargetTypeVGroup
	_AuthenticationMethodTargetTypePUnknownFutureValue = AuthenticationMethodTargetTypeVUnknownFutureValue
)

// AuthenticationPhoneType undocumented
type AuthenticationPhoneType string

const (
	// AuthenticationPhoneTypeVMobile undocumented
	AuthenticationPhoneTypeVMobile AuthenticationPhoneType = "mobile"
	// AuthenticationPhoneTypeVAlternateMobile undocumented
	AuthenticationPhoneTypeVAlternateMobile AuthenticationPhoneType = "alternateMobile"
	// AuthenticationPhoneTypeVOffice undocumented
	AuthenticationPhoneTypeVOffice AuthenticationPhoneType = "office"
	// AuthenticationPhoneTypeVUnknownFutureValue undocumented
	AuthenticationPhoneTypeVUnknownFutureValue AuthenticationPhoneType = "unknownFutureValue"
)

var (
	// AuthenticationPhoneTypePMobile is a pointer to AuthenticationPhoneTypeVMobile
	AuthenticationPhoneTypePMobile = &_AuthenticationPhoneTypePMobile
	// AuthenticationPhoneTypePAlternateMobile is a pointer to AuthenticationPhoneTypeVAlternateMobile
	AuthenticationPhoneTypePAlternateMobile = &_AuthenticationPhoneTypePAlternateMobile
	// AuthenticationPhoneTypePOffice is a pointer to AuthenticationPhoneTypeVOffice
	AuthenticationPhoneTypePOffice = &_AuthenticationPhoneTypePOffice
	// AuthenticationPhoneTypePUnknownFutureValue is a pointer to AuthenticationPhoneTypeVUnknownFutureValue
	AuthenticationPhoneTypePUnknownFutureValue = &_AuthenticationPhoneTypePUnknownFutureValue
)

var (
	_AuthenticationPhoneTypePMobile             = AuthenticationPhoneTypeVMobile
	_AuthenticationPhoneTypePAlternateMobile    = AuthenticationPhoneTypeVAlternateMobile
	_AuthenticationPhoneTypePOffice             = AuthenticationPhoneTypeVOffice
	_AuthenticationPhoneTypePUnknownFutureValue = AuthenticationPhoneTypeVUnknownFutureValue
)

// AuthenticationTransformConstant undocumented
type AuthenticationTransformConstant string

const (
	// AuthenticationTransformConstantVMd5_96 undocumented
	AuthenticationTransformConstantVMd5_96 AuthenticationTransformConstant = "md5_96"
	// AuthenticationTransformConstantVSha1_96 undocumented
	AuthenticationTransformConstantVSha1_96 AuthenticationTransformConstant = "sha1_96"
	// AuthenticationTransformConstantVSha_256_128 undocumented
	AuthenticationTransformConstantVSha_256_128 AuthenticationTransformConstant = "sha_256_128"
	// AuthenticationTransformConstantVAes128Gcm undocumented
	AuthenticationTransformConstantVAes128Gcm AuthenticationTransformConstant = "aes128Gcm"
	// AuthenticationTransformConstantVAes192Gcm undocumented
	AuthenticationTransformConstantVAes192Gcm AuthenticationTransformConstant = "aes192Gcm"
	// AuthenticationTransformConstantVAes256Gcm undocumented
	AuthenticationTransformConstantVAes256Gcm AuthenticationTransformConstant = "aes256Gcm"
)

var (
	// AuthenticationTransformConstantPMd5_96 is a pointer to AuthenticationTransformConstantVMd5_96
	AuthenticationTransformConstantPMd5_96 = &_AuthenticationTransformConstantPMd5_96
	// AuthenticationTransformConstantPSha1_96 is a pointer to AuthenticationTransformConstantVSha1_96
	AuthenticationTransformConstantPSha1_96 = &_AuthenticationTransformConstantPSha1_96
	// AuthenticationTransformConstantPSha_256_128 is a pointer to AuthenticationTransformConstantVSha_256_128
	AuthenticationTransformConstantPSha_256_128 = &_AuthenticationTransformConstantPSha_256_128
	// AuthenticationTransformConstantPAes128Gcm is a pointer to AuthenticationTransformConstantVAes128Gcm
	AuthenticationTransformConstantPAes128Gcm = &_AuthenticationTransformConstantPAes128Gcm
	// AuthenticationTransformConstantPAes192Gcm is a pointer to AuthenticationTransformConstantVAes192Gcm
	AuthenticationTransformConstantPAes192Gcm = &_AuthenticationTransformConstantPAes192Gcm
	// AuthenticationTransformConstantPAes256Gcm is a pointer to AuthenticationTransformConstantVAes256Gcm
	AuthenticationTransformConstantPAes256Gcm = &_AuthenticationTransformConstantPAes256Gcm
)

var (
	_AuthenticationTransformConstantPMd5_96      = AuthenticationTransformConstantVMd5_96
	_AuthenticationTransformConstantPSha1_96     = AuthenticationTransformConstantVSha1_96
	_AuthenticationTransformConstantPSha_256_128 = AuthenticationTransformConstantVSha_256_128
	_AuthenticationTransformConstantPAes128Gcm   = AuthenticationTransformConstantVAes128Gcm
	_AuthenticationTransformConstantPAes192Gcm   = AuthenticationTransformConstantVAes192Gcm
	_AuthenticationTransformConstantPAes256Gcm   = AuthenticationTransformConstantVAes256Gcm
)
