// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Planner undocumented
type Planner struct {
	// Object is the base model of Planner
	Object
	// Buckets undocumented
	Buckets []PlannerBucket `json:"buckets,omitempty"`
	// Plans undocumented
	Plans []PlannerPlan `json:"plans,omitempty"`
	// Rosters undocumented
	Rosters []PlannerRoster `json:"rosters,omitempty"`
	// Tasks undocumented
	Tasks []PlannerTask `json:"tasks,omitempty"`
}

// PlannerAppliedCategories undocumented
type PlannerAppliedCategories struct {
	// Object is the base model of PlannerAppliedCategories
	Object
}

// PlannerAssignedToTaskBoardTaskFormat undocumented
type PlannerAssignedToTaskBoardTaskFormat struct {
	// PlannerDelta is the base model of PlannerAssignedToTaskBoardTaskFormat
	PlannerDelta
	// OrderHintsByAssignee undocumented
	OrderHintsByAssignee *PlannerOrderHintsByAssignee `json:"orderHintsByAssignee,omitempty"`
	// UnassignedOrderHint undocumented
	UnassignedOrderHint *string `json:"unassignedOrderHint,omitempty"`
}

// PlannerAssignment undocumented
type PlannerAssignment struct {
	// Object is the base model of PlannerAssignment
	Object
	// AssignedBy undocumented
	AssignedBy *IdentitySet `json:"assignedBy,omitempty"`
	// AssignedDateTime undocumented
	AssignedDateTime *time.Time `json:"assignedDateTime,omitempty"`
	// OrderHint undocumented
	OrderHint *string `json:"orderHint,omitempty"`
}

// PlannerAssignments undocumented
type PlannerAssignments struct {
	// Object is the base model of PlannerAssignments
	Object
}

// PlannerBucket undocumented
type PlannerBucket struct {
	// PlannerDelta is the base model of PlannerBucket
	PlannerDelta
	// Name undocumented
	Name *string `json:"name,omitempty"`
	// OrderHint undocumented
	OrderHint *string `json:"orderHint,omitempty"`
	// PlanID undocumented
	PlanID *string `json:"planId,omitempty"`
	// Tasks undocumented
	Tasks []PlannerTask `json:"tasks,omitempty"`
}

// PlannerBucketTaskBoardTaskFormat undocumented
type PlannerBucketTaskBoardTaskFormat struct {
	// PlannerDelta is the base model of PlannerBucketTaskBoardTaskFormat
	PlannerDelta
	// OrderHint undocumented
	OrderHint *string `json:"orderHint,omitempty"`
}

// PlannerCategoryDescriptions undocumented
type PlannerCategoryDescriptions struct {
	// Object is the base model of PlannerCategoryDescriptions
	Object
	// Category1 undocumented
	Category1 *string `json:"category1,omitempty"`
	// Category10 undocumented
	Category10 *string `json:"category10,omitempty"`
	// Category11 undocumented
	Category11 *string `json:"category11,omitempty"`
	// Category12 undocumented
	Category12 *string `json:"category12,omitempty"`
	// Category13 undocumented
	Category13 *string `json:"category13,omitempty"`
	// Category14 undocumented
	Category14 *string `json:"category14,omitempty"`
	// Category15 undocumented
	Category15 *string `json:"category15,omitempty"`
	// Category16 undocumented
	Category16 *string `json:"category16,omitempty"`
	// Category17 undocumented
	Category17 *string `json:"category17,omitempty"`
	// Category18 undocumented
	Category18 *string `json:"category18,omitempty"`
	// Category19 undocumented
	Category19 *string `json:"category19,omitempty"`
	// Category2 undocumented
	Category2 *string `json:"category2,omitempty"`
	// Category20 undocumented
	Category20 *string `json:"category20,omitempty"`
	// Category21 undocumented
	Category21 *string `json:"category21,omitempty"`
	// Category22 undocumented
	Category22 *string `json:"category22,omitempty"`
	// Category23 undocumented
	Category23 *string `json:"category23,omitempty"`
	// Category24 undocumented
	Category24 *string `json:"category24,omitempty"`
	// Category25 undocumented
	Category25 *string `json:"category25,omitempty"`
	// Category3 undocumented
	Category3 *string `json:"category3,omitempty"`
	// Category4 undocumented
	Category4 *string `json:"category4,omitempty"`
	// Category5 undocumented
	Category5 *string `json:"category5,omitempty"`
	// Category6 undocumented
	Category6 *string `json:"category6,omitempty"`
	// Category7 undocumented
	Category7 *string `json:"category7,omitempty"`
	// Category8 undocumented
	Category8 *string `json:"category8,omitempty"`
	// Category9 undocumented
	Category9 *string `json:"category9,omitempty"`
}

// PlannerChecklistItem undocumented
type PlannerChecklistItem struct {
	// Object is the base model of PlannerChecklistItem
	Object
	// IsChecked undocumented
	IsChecked *bool `json:"isChecked,omitempty"`
	// LastModifiedBy undocumented
	LastModifiedBy *IdentitySet `json:"lastModifiedBy,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// OrderHint undocumented
	OrderHint *string `json:"orderHint,omitempty"`
	// Title undocumented
	Title *string `json:"title,omitempty"`
}

// PlannerChecklistItems undocumented
type PlannerChecklistItems struct {
	// Object is the base model of PlannerChecklistItems
	Object
}

// PlannerDelta undocumented
type PlannerDelta struct {
	// Entity is the base model of PlannerDelta
	Entity
}

// PlannerExternalReference undocumented
type PlannerExternalReference struct {
	// Object is the base model of PlannerExternalReference
	Object
	// Alias undocumented
	Alias *string `json:"alias,omitempty"`
	// LastModifiedBy undocumented
	LastModifiedBy *IdentitySet `json:"lastModifiedBy,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// PreviewPriority undocumented
	PreviewPriority *string `json:"previewPriority,omitempty"`
	// Type undocumented
	Type *string `json:"type,omitempty"`
}

// PlannerExternalReferences undocumented
type PlannerExternalReferences struct {
	// Object is the base model of PlannerExternalReferences
	Object
}

// PlannerFavoritePlanReference undocumented
type PlannerFavoritePlanReference struct {
	// Object is the base model of PlannerFavoritePlanReference
	Object
	// OrderHint undocumented
	OrderHint *string `json:"orderHint,omitempty"`
	// PlanTitle undocumented
	PlanTitle *string `json:"planTitle,omitempty"`
}

// PlannerFavoritePlanReferenceCollection undocumented
type PlannerFavoritePlanReferenceCollection struct {
	// Object is the base model of PlannerFavoritePlanReferenceCollection
	Object
}

// PlannerGroup undocumented
type PlannerGroup struct {
	// Entity is the base model of PlannerGroup
	Entity
	// Plans undocumented
	Plans []PlannerPlan `json:"plans,omitempty"`
}

// PlannerOrderHintsByAssignee undocumented
type PlannerOrderHintsByAssignee struct {
	// Object is the base model of PlannerOrderHintsByAssignee
	Object
}

// PlannerPlan undocumented
type PlannerPlan struct {
	// PlannerDelta is the base model of PlannerPlan
	PlannerDelta
	// Container undocumented
	Container *PlannerPlanContainer `json:"container,omitempty"`
	// Contexts undocumented
	Contexts *PlannerPlanContextCollection `json:"contexts,omitempty"`
	// CreatedBy undocumented
	CreatedBy *IdentitySet `json:"createdBy,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// Owner undocumented
	Owner *string `json:"owner,omitempty"`
	// Title undocumented
	Title *string `json:"title,omitempty"`
	// Buckets undocumented
	Buckets []PlannerBucket `json:"buckets,omitempty"`
	// Details undocumented
	Details *PlannerPlanDetails `json:"details,omitempty"`
	// Tasks undocumented
	Tasks []PlannerTask `json:"tasks,omitempty"`
}

// PlannerPlanContainer undocumented
type PlannerPlanContainer struct {
	// Object is the base model of PlannerPlanContainer
	Object
	// ContainerID undocumented
	ContainerID *string `json:"containerId,omitempty"`
	// Type undocumented
	Type *PlannerContainerType `json:"type,omitempty"`
	// URL undocumented
	URL *string `json:"url,omitempty"`
}

// PlannerPlanContext undocumented
type PlannerPlanContext struct {
	// Object is the base model of PlannerPlanContext
	Object
	// AssociationType undocumented
	AssociationType *string `json:"associationType,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// DisplayNameSegments undocumented
	DisplayNameSegments []string `json:"displayNameSegments,omitempty"`
	// IsCreationContext undocumented
	IsCreationContext *bool `json:"isCreationContext,omitempty"`
	// OwnerAppID undocumented
	OwnerAppID *string `json:"ownerAppId,omitempty"`
}

// PlannerPlanContextCollection undocumented
type PlannerPlanContextCollection struct {
	// Object is the base model of PlannerPlanContextCollection
	Object
}

// PlannerPlanContextDetails undocumented
type PlannerPlanContextDetails struct {
	// Object is the base model of PlannerPlanContextDetails
	Object
	// CustomLinkText undocumented
	CustomLinkText *string `json:"customLinkText,omitempty"`
	// DisplayLinkType undocumented
	DisplayLinkType *PlannerPlanContextType `json:"displayLinkType,omitempty"`
	// URL undocumented
	URL *string `json:"url,omitempty"`
}

// PlannerPlanContextDetailsCollection undocumented
type PlannerPlanContextDetailsCollection struct {
	// Object is the base model of PlannerPlanContextDetailsCollection
	Object
}

// PlannerPlanDetails undocumented
type PlannerPlanDetails struct {
	// PlannerDelta is the base model of PlannerPlanDetails
	PlannerDelta
	// CategoryDescriptions undocumented
	CategoryDescriptions *PlannerCategoryDescriptions `json:"categoryDescriptions,omitempty"`
	// ContextDetails undocumented
	ContextDetails *PlannerPlanContextDetailsCollection `json:"contextDetails,omitempty"`
	// SharedWith undocumented
	SharedWith *PlannerUserIDs `json:"sharedWith,omitempty"`
}

// PlannerProgressTaskBoardTaskFormat undocumented
type PlannerProgressTaskBoardTaskFormat struct {
	// PlannerDelta is the base model of PlannerProgressTaskBoardTaskFormat
	PlannerDelta
	// OrderHint undocumented
	OrderHint *string `json:"orderHint,omitempty"`
}

// PlannerRecentPlanReference undocumented
type PlannerRecentPlanReference struct {
	// Object is the base model of PlannerRecentPlanReference
	Object
	// LastAccessedDateTime undocumented
	LastAccessedDateTime *time.Time `json:"lastAccessedDateTime,omitempty"`
	// PlanTitle undocumented
	PlanTitle *string `json:"planTitle,omitempty"`
}

// PlannerRecentPlanReferenceCollection undocumented
type PlannerRecentPlanReferenceCollection struct {
	// Object is the base model of PlannerRecentPlanReferenceCollection
	Object
}

// PlannerRoster undocumented
type PlannerRoster struct {
	// Entity is the base model of PlannerRoster
	Entity
	// Members undocumented
	Members []PlannerRosterMember `json:"members,omitempty"`
	// Plans undocumented
	Plans []PlannerPlan `json:"plans,omitempty"`
}

// PlannerRosterMember undocumented
type PlannerRosterMember struct {
	// Entity is the base model of PlannerRosterMember
	Entity
	// Roles undocumented
	Roles []string `json:"roles,omitempty"`
	// TenantID undocumented
	TenantID *string `json:"tenantId,omitempty"`
	// UserID undocumented
	UserID *string `json:"userId,omitempty"`
}

// PlannerTask undocumented
type PlannerTask struct {
	// PlannerDelta is the base model of PlannerTask
	PlannerDelta
	// ActiveChecklistItemCount undocumented
	ActiveChecklistItemCount *int `json:"activeChecklistItemCount,omitempty"`
	// AppliedCategories undocumented
	AppliedCategories *PlannerAppliedCategories `json:"appliedCategories,omitempty"`
	// AssigneePriority undocumented
	AssigneePriority *string `json:"assigneePriority,omitempty"`
	// Assignments undocumented
	Assignments *PlannerAssignments `json:"assignments,omitempty"`
	// BucketID undocumented
	BucketID *string `json:"bucketId,omitempty"`
	// ChecklistItemCount undocumented
	ChecklistItemCount *int `json:"checklistItemCount,omitempty"`
	// CompletedBy undocumented
	CompletedBy *IdentitySet `json:"completedBy,omitempty"`
	// CompletedDateTime undocumented
	CompletedDateTime *time.Time `json:"completedDateTime,omitempty"`
	// ConversationThreadID undocumented
	ConversationThreadID *string `json:"conversationThreadId,omitempty"`
	// CreatedBy undocumented
	CreatedBy *IdentitySet `json:"createdBy,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// CreationSource undocumented
	CreationSource *PlannerTaskCreation `json:"creationSource,omitempty"`
	// DueDateTime undocumented
	DueDateTime *time.Time `json:"dueDateTime,omitempty"`
	// HasDescription undocumented
	HasDescription *bool `json:"hasDescription,omitempty"`
	// OrderHint undocumented
	OrderHint *string `json:"orderHint,omitempty"`
	// PercentComplete undocumented
	PercentComplete *int `json:"percentComplete,omitempty"`
	// PlanID undocumented
	PlanID *string `json:"planId,omitempty"`
	// PreviewType undocumented
	PreviewType *PlannerPreviewType `json:"previewType,omitempty"`
	// Priority undocumented
	Priority *int `json:"priority,omitempty"`
	// ReferenceCount undocumented
	ReferenceCount *int `json:"referenceCount,omitempty"`
	// StartDateTime undocumented
	StartDateTime *time.Time `json:"startDateTime,omitempty"`
	// Title undocumented
	Title *string `json:"title,omitempty"`
	// AssignedToTaskBoardFormat undocumented
	AssignedToTaskBoardFormat *PlannerAssignedToTaskBoardTaskFormat `json:"assignedToTaskBoardFormat,omitempty"`
	// BucketTaskBoardFormat undocumented
	BucketTaskBoardFormat *PlannerBucketTaskBoardTaskFormat `json:"bucketTaskBoardFormat,omitempty"`
	// Details undocumented
	Details *PlannerTaskDetails `json:"details,omitempty"`
	// ProgressTaskBoardFormat undocumented
	ProgressTaskBoardFormat *PlannerProgressTaskBoardTaskFormat `json:"progressTaskBoardFormat,omitempty"`
}

// PlannerTaskCreation undocumented
type PlannerTaskCreation struct {
	// Object is the base model of PlannerTaskCreation
	Object
	// TeamsPublicationInfo undocumented
	TeamsPublicationInfo *PlannerTeamsPublicationInfo `json:"teamsPublicationInfo,omitempty"`
}

// PlannerTaskDetails undocumented
type PlannerTaskDetails struct {
	// PlannerDelta is the base model of PlannerTaskDetails
	PlannerDelta
	// Checklist undocumented
	Checklist *PlannerChecklistItems `json:"checklist,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// PreviewType undocumented
	PreviewType *PlannerPreviewType `json:"previewType,omitempty"`
	// References undocumented
	References *PlannerExternalReferences `json:"references,omitempty"`
}

// PlannerTeamsPublicationInfo undocumented
type PlannerTeamsPublicationInfo struct {
	// Object is the base model of PlannerTeamsPublicationInfo
	Object
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// PublicationID undocumented
	PublicationID *string `json:"publicationId,omitempty"`
	// PublishedToPlanID undocumented
	PublishedToPlanID *string `json:"publishedToPlanId,omitempty"`
	// PublishingTeamID undocumented
	PublishingTeamID *string `json:"publishingTeamId,omitempty"`
	// PublishingTeamName undocumented
	PublishingTeamName *string `json:"publishingTeamName,omitempty"`
}

// PlannerUser undocumented
type PlannerUser struct {
	// PlannerDelta is the base model of PlannerUser
	PlannerDelta
	// FavoritePlanReferences undocumented
	FavoritePlanReferences *PlannerFavoritePlanReferenceCollection `json:"favoritePlanReferences,omitempty"`
	// RecentPlanReferences undocumented
	RecentPlanReferences *PlannerRecentPlanReferenceCollection `json:"recentPlanReferences,omitempty"`
	// All undocumented
	All []PlannerDelta `json:"all,omitempty"`
	// FavoritePlans undocumented
	FavoritePlans []PlannerPlan `json:"favoritePlans,omitempty"`
	// Plans undocumented
	Plans []PlannerPlan `json:"plans,omitempty"`
	// RecentPlans undocumented
	RecentPlans []PlannerPlan `json:"recentPlans,omitempty"`
	// RosterPlans undocumented
	RosterPlans []PlannerPlan `json:"rosterPlans,omitempty"`
	// Tasks undocumented
	Tasks []PlannerTask `json:"tasks,omitempty"`
}

// PlannerUserIDs undocumented
type PlannerUserIDs struct {
	// Object is the base model of PlannerUserIDs
	Object
}
