// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// TextClassificationRequestObject undocumented
type TextClassificationRequestObject struct {
	// Entity is the base model of TextClassificationRequestObject
	Entity
	// FileExtension undocumented
	FileExtension *string `json:"fileExtension,omitempty"`
	// MatchTolerancesToInclude undocumented
	MatchTolerancesToInclude *MlClassificationMatchTolerance `json:"matchTolerancesToInclude,omitempty"`
	// ScopesToRun undocumented
	ScopesToRun *SensitiveTypeScope `json:"scopesToRun,omitempty"`
	// SensitiveTypeIDs undocumented
	SensitiveTypeIDs []string `json:"sensitiveTypeIds,omitempty"`
	// Text undocumented
	Text *string `json:"text,omitempty"`
}

// TextColumn undocumented
type TextColumn struct {
	// Object is the base model of TextColumn
	Object
	// AllowMultipleLines undocumented
	AllowMultipleLines *bool `json:"allowMultipleLines,omitempty"`
	// AppendChangesToExistingText undocumented
	AppendChangesToExistingText *bool `json:"appendChangesToExistingText,omitempty"`
	// LinesForEditing undocumented
	LinesForEditing *int `json:"linesForEditing,omitempty"`
	// MaxLength undocumented
	MaxLength *int `json:"maxLength,omitempty"`
	// TextType undocumented
	TextType *string `json:"textType,omitempty"`
}
