// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// ExtendedKeyUsage Custom Extended Key Usage definition
type ExtendedKeyUsage struct {
	// Object is the base model of ExtendedKeyUsage
	Object
	// Name Extended Key Usage Name
	Name *string `json:"name,omitempty"`
	// ObjectIdentifier Extended Key Usage Object Identifier
	ObjectIdentifier *string `json:"objectIdentifier,omitempty"`
}
