// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// SingleSignOnExtension Represents an Apple Single Sign-On Extension.
type SingleSignOnExtension struct {
	// Object is the base model of SingleSignOnExtension
	Object
}

// SingleUser undocumented
type SingleUser struct {
	// UserSet is the base model of SingleUser
	UserSet
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// ID undocumented
	ID *string `json:"id,omitempty"`
}

// SingleValueLegacyExtendedProperty undocumented
type SingleValueLegacyExtendedProperty struct {
	// Entity is the base model of SingleValueLegacyExtendedProperty
	Entity
	// Value undocumented
	Value *string `json:"value,omitempty"`
}
