// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// RetireScheduledManagedDevice ManagedDevices that are scheduled for retire
type RetireScheduledManagedDevice struct {
	// Object is the base model of RetireScheduledManagedDevice
	Object
	// ComplianceState Managed Device ComplianceStatus
	ComplianceState *ComplianceStatus `json:"complianceState,omitempty"`
	// DeviceCompliancePolicyID Device Compliance PolicyId
	DeviceCompliancePolicyID *string `json:"deviceCompliancePolicyId,omitempty"`
	// DeviceCompliancePolicyName Device Compliance Policy Name
	DeviceCompliancePolicyName *string `json:"deviceCompliancePolicyName,omitempty"`
	// DeviceType Managed Device Device Type
	DeviceType *DeviceType `json:"deviceType,omitempty"`
	// ID Key of the entity.
	ID *string `json:"id,omitempty"`
	// ManagedDeviceID Managed DeviceId
	ManagedDeviceID *string `json:"managedDeviceId,omitempty"`
	// ManagedDeviceName Managed Device Name
	ManagedDeviceName *string `json:"managedDeviceName,omitempty"`
	// ManagementAgent Managed Device ManagementAgentType
	ManagementAgent *ManagementAgentType `json:"managementAgent,omitempty"`
	// OwnerType Managed Device ManagedDeviceOwnerType
	OwnerType *ManagedDeviceOwnerType `json:"ownerType,omitempty"`
	// RetireAfterDateTime Managed Device Retire After DateTime
	RetireAfterDateTime *time.Time `json:"retireAfterDateTime,omitempty"`
	// RoleScopeTagIDs List of Scope Tags for this Entity instance.
	RoleScopeTagIDs []string `json:"roleScopeTagIds,omitempty"`
}
