// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// ClientCertificateAuthentication undocumented
type ClientCertificateAuthentication struct {
	// APIAuthenticationConfigurationBase is the base model of ClientCertificateAuthentication
	APIAuthenticationConfigurationBase
	// CertificateList undocumented
	CertificateList []Pkcs12CertificateInformation `json:"certificateList,omitempty"`
}

// ClientUserAgent undocumented
type ClientUserAgent struct {
	// UserAgent is the base model of ClientUserAgent
	UserAgent
	// Platform undocumented
	Platform *ClientPlatform `json:"platform,omitempty"`
	// ProductFamily undocumented
	ProductFamily *ProductFamily `json:"productFamily,omitempty"`
}
