// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// UsageDetails undocumented
type UsageDetails struct {
	// Object is the base model of UsageDetails
	Object
	// LastAccessedDateTime undocumented
	LastAccessedDateTime *time.Time `json:"lastAccessedDateTime,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
}

// UsageRight undocumented
type UsageRight struct {
	// Entity is the base model of UsageRight
	Entity
	// CatalogID undocumented
	CatalogID *string `json:"catalogId,omitempty"`
	// ServiceIdentifier undocumented
	ServiceIdentifier *string `json:"serviceIdentifier,omitempty"`
	// State undocumented
	State *UsageRightState `json:"state,omitempty"`
}
