// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// SpecifiedCaptiveNetworkPlugins Specifies all the Captive network plugins allowed during the IKEv2 AlwaysOn VPN connection
type SpecifiedCaptiveNetworkPlugins struct {
	// Object is the base model of SpecifiedCaptiveNetworkPlugins
	Object
	// AllowedBundleIdentifiers Address of the IKEv2 server. Must be a FQDN, UserFQDN, network address, or ASN1DN
	AllowedBundleIdentifiers []string `json:"allowedBundleIdentifiers,omitempty"`
}
