// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// SensitivityLabel undocumented
type SensitivityLabel struct {
	// Entity is the base model of SensitivityLabel
	Entity
	// ApplicableTo undocumented
	ApplicableTo *SensitivityLabelTarget `json:"applicableTo,omitempty"`
	// ApplicationMode undocumented
	ApplicationMode *ApplicationMode `json:"applicationMode,omitempty"`
	// AssignedPolicies undocumented
	AssignedPolicies []LabelPolicy `json:"assignedPolicies,omitempty"`
	// AutoLabeling undocumented
	AutoLabeling *AutoLabeling `json:"autoLabeling,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// IsDefault undocumented
	IsDefault *bool `json:"isDefault,omitempty"`
	// IsEndpointProtectionEnabled undocumented
	IsEndpointProtectionEnabled *bool `json:"isEndpointProtectionEnabled,omitempty"`
	// LabelActions undocumented
	LabelActions []LabelActionBase `json:"labelActions,omitempty"`
	// Name undocumented
	Name *string `json:"name,omitempty"`
	// Priority undocumented
	Priority *int `json:"priority,omitempty"`
	// ToolTip undocumented
	ToolTip *string `json:"toolTip,omitempty"`
	// Sublabels undocumented
	Sublabels []SensitivityLabel `json:"sublabels,omitempty"`
}

// SensitivityPolicySettings undocumented
type SensitivityPolicySettings struct {
	// Entity is the base model of SensitivityPolicySettings
	Entity
	// ApplicableTo undocumented
	ApplicableTo *SensitivityLabelTarget `json:"applicableTo,omitempty"`
	// DowngradeSensitivityRequiresJustification undocumented
	DowngradeSensitivityRequiresJustification *bool `json:"downgradeSensitivityRequiresJustification,omitempty"`
	// HelpWebURL undocumented
	HelpWebURL *string `json:"helpWebUrl,omitempty"`
	// IsMandatory undocumented
	IsMandatory *bool `json:"isMandatory,omitempty"`
}
