// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// OcrSettings undocumented
type OcrSettings struct {
	// Object is the base model of OcrSettings
	Object
	// IsEnabled undocumented
	IsEnabled *bool `json:"isEnabled,omitempty"`
	// MaxImageSize undocumented
	MaxImageSize *int `json:"maxImageSize,omitempty"`
	// Timeout undocumented
	Timeout *Duration `json:"timeout,omitempty"`
}
