// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// FeatureRolloutPolicy undocumented
type FeatureRolloutPolicy struct {
	// Entity is the base model of FeatureRolloutPolicy
	Entity
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// Feature undocumented
	Feature *StagedFeatureName `json:"feature,omitempty"`
	// IsAppliedToOrganization undocumented
	IsAppliedToOrganization *bool `json:"isAppliedToOrganization,omitempty"`
	// IsEnabled undocumented
	IsEnabled *bool `json:"isEnabled,omitempty"`
	// AppliesTo undocumented
	AppliesTo []DirectoryObject `json:"appliesTo,omitempty"`
}

// FeatureUpdateCatalogEntry undocumented
type FeatureUpdateCatalogEntry struct {
	// SoftwareUpdateCatalogEntry is the base model of FeatureUpdateCatalogEntry
	SoftwareUpdateCatalogEntry
	// Version undocumented
	Version *string `json:"version,omitempty"`
}

// FeatureUpdateReference undocumented
type FeatureUpdateReference struct {
	// WindowsUpdateReference is the base model of FeatureUpdateReference
	WindowsUpdateReference
	// Version undocumented
	Version *string `json:"version,omitempty"`
}

// FeatureUsageDetail undocumented
type FeatureUsageDetail struct {
	// Object is the base model of FeatureUsageDetail
	Object
	// FeatureName undocumented
	FeatureName *string `json:"featureName,omitempty"`
	// LastConfiguredDateTime undocumented
	LastConfiguredDateTime *time.Time `json:"lastConfiguredDateTime,omitempty"`
	// LastUsedDateTime undocumented
	LastUsedDateTime *time.Time `json:"lastUsedDateTime,omitempty"`
	// LicenseAssigned undocumented
	LicenseAssigned *AzureADLicenseType `json:"licenseAssigned,omitempty"`
	// LicenseRequired undocumented
	LicenseRequired *AzureADLicenseType `json:"licenseRequired,omitempty"`
}
