// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// UnaryManagementConditionExpression A management condition expression that is evaluated using a unary operation.
type UnaryManagementConditionExpression struct {
	// ManagementConditionExpressionModel is the base model of UnaryManagementConditionExpression
	ManagementConditionExpressionModel
	// Operand The operand of the unary operation.
	Operand *ManagementConditionExpressionModel `json:"operand,omitempty"`
	// Operator The operator used in the evaluation of the unary operation.
	Operator *UnaryManagementConditionExpressionOperatorType `json:"operator,omitempty"`
}
