// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Tag undocumented
type Tag struct {
	// Entity is the base model of Tag
	Entity
	// ChildSelectability undocumented
	ChildSelectability *ChildSelectability `json:"childSelectability,omitempty"`
	// CreatedBy undocumented
	CreatedBy *IdentitySet `json:"createdBy,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// ChildTags undocumented
	ChildTags []Tag `json:"childTags,omitempty"`
	// Parent undocumented
	Parent *Tag `json:"parent,omitempty"`
}

// TagOperation undocumented
type TagOperation struct {
	// CaseOperation is the base model of TagOperation
	CaseOperation
}
