// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Segment undocumented
type Segment struct {
	// Entity is the base model of Segment
	Entity
	// Callee undocumented
	Callee *Endpoint `json:"callee,omitempty"`
	// Caller undocumented
	Caller *Endpoint `json:"caller,omitempty"`
	// EndDateTime undocumented
	EndDateTime *time.Time `json:"endDateTime,omitempty"`
	// FailureInfo undocumented
	FailureInfo *FailureInfo `json:"failureInfo,omitempty"`
	// Media undocumented
	Media []Media `json:"media,omitempty"`
	// StartDateTime undocumented
	StartDateTime *time.Time `json:"startDateTime,omitempty"`
}
