// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// LoggedOnUser Logged On User
type LoggedOnUser struct {
	// Object is the base model of LoggedOnUser
	Object
	// LastLogOnDateTime Date time when user logs on
	LastLogOnDateTime *time.Time `json:"lastLogOnDateTime,omitempty"`
	// UserID User id
	UserID *string `json:"userId,omitempty"`
}
