// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// OneDriveActivityUserDetail undocumented
type OneDriveActivityUserDetail struct {
	// Entity is the base model of OneDriveActivityUserDetail
	Entity
	// AssignedProducts undocumented
	AssignedProducts []string `json:"assignedProducts,omitempty"`
	// DeletedDate undocumented
	DeletedDate *Date `json:"deletedDate,omitempty"`
	// IsDeleted undocumented
	IsDeleted *bool `json:"isDeleted,omitempty"`
	// LastActivityDate undocumented
	LastActivityDate *Date `json:"lastActivityDate,omitempty"`
	// ReportPeriod undocumented
	ReportPeriod *string `json:"reportPeriod,omitempty"`
	// ReportRefreshDate undocumented
	ReportRefreshDate *Date `json:"reportRefreshDate,omitempty"`
	// SharedExternallyFileCount undocumented
	SharedExternallyFileCount *int `json:"sharedExternallyFileCount,omitempty"`
	// SharedInternallyFileCount undocumented
	SharedInternallyFileCount *int `json:"sharedInternallyFileCount,omitempty"`
	// SyncedFileCount undocumented
	SyncedFileCount *int `json:"syncedFileCount,omitempty"`
	// UserPrincipalName undocumented
	UserPrincipalName *string `json:"userPrincipalName,omitempty"`
	// ViewedOrEditedFileCount undocumented
	ViewedOrEditedFileCount *int `json:"viewedOrEditedFileCount,omitempty"`
}

// OneDriveUsageAccountCounts undocumented
type OneDriveUsageAccountCounts struct {
	// Entity is the base model of OneDriveUsageAccountCounts
	Entity
	// Active undocumented
	Active *int `json:"active,omitempty"`
	// ReportDate undocumented
	ReportDate *Date `json:"reportDate,omitempty"`
	// ReportPeriod undocumented
	ReportPeriod *string `json:"reportPeriod,omitempty"`
	// ReportRefreshDate undocumented
	ReportRefreshDate *Date `json:"reportRefreshDate,omitempty"`
	// SiteType undocumented
	SiteType *string `json:"siteType,omitempty"`
	// Total undocumented
	Total *int `json:"total,omitempty"`
}

// OneDriveUsageAccountDetail undocumented
type OneDriveUsageAccountDetail struct {
	// Entity is the base model of OneDriveUsageAccountDetail
	Entity
	// ActiveFileCount undocumented
	ActiveFileCount *int `json:"activeFileCount,omitempty"`
	// FileCount undocumented
	FileCount *int `json:"fileCount,omitempty"`
	// IsDeleted undocumented
	IsDeleted *bool `json:"isDeleted,omitempty"`
	// LastActivityDate undocumented
	LastActivityDate *Date `json:"lastActivityDate,omitempty"`
	// OwnerDisplayName undocumented
	OwnerDisplayName *string `json:"ownerDisplayName,omitempty"`
	// OwnerPrincipalName undocumented
	OwnerPrincipalName *string `json:"ownerPrincipalName,omitempty"`
	// ReportPeriod undocumented
	ReportPeriod *string `json:"reportPeriod,omitempty"`
	// ReportRefreshDate undocumented
	ReportRefreshDate *Date `json:"reportRefreshDate,omitempty"`
	// SiteURL undocumented
	SiteURL *string `json:"siteUrl,omitempty"`
	// StorageAllocatedInBytes undocumented
	StorageAllocatedInBytes *int `json:"storageAllocatedInBytes,omitempty"`
	// StorageUsedInBytes undocumented
	StorageUsedInBytes *int `json:"storageUsedInBytes,omitempty"`
}

// OneDriveUsageFileCounts undocumented
type OneDriveUsageFileCounts struct {
	// Entity is the base model of OneDriveUsageFileCounts
	Entity
	// Active undocumented
	Active *int `json:"active,omitempty"`
	// ReportDate undocumented
	ReportDate *Date `json:"reportDate,omitempty"`
	// ReportPeriod undocumented
	ReportPeriod *string `json:"reportPeriod,omitempty"`
	// ReportRefreshDate undocumented
	ReportRefreshDate *Date `json:"reportRefreshDate,omitempty"`
	// SiteType undocumented
	SiteType *string `json:"siteType,omitempty"`
	// Total undocumented
	Total *int `json:"total,omitempty"`
}
