// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Deployment undocumented
type Deployment struct {
	// Entity is the base model of Deployment
	Entity
	// Content undocumented
	Content *DeployableContent `json:"content,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// Settings undocumented
	Settings *DeploymentSettings `json:"settings,omitempty"`
	// State undocumented
	State *DeploymentState `json:"state,omitempty"`
	// Audience undocumented
	Audience *DeploymentAudience `json:"audience,omitempty"`
}

// DeploymentAudience undocumented
type DeploymentAudience struct {
	// Entity is the base model of DeploymentAudience
	Entity
	// Exclusions undocumented
	Exclusions []UpdatableAsset `json:"exclusions,omitempty"`
	// Members undocumented
	Members []UpdatableAsset `json:"members,omitempty"`
}

// DeploymentSettings undocumented
type DeploymentSettings struct {
	// Object is the base model of DeploymentSettings
	Object
	// Monitoring undocumented
	Monitoring *MonitoringSettings `json:"monitoring,omitempty"`
	// Rollout undocumented
	Rollout *RolloutSettings `json:"rollout,omitempty"`
}

// DeploymentState undocumented
type DeploymentState struct {
	// Object is the base model of DeploymentState
	Object
	// Reasons undocumented
	Reasons []DeploymentStateReason `json:"reasons,omitempty"`
	// RequestedValue undocumented
	RequestedValue *RequestedDeploymentStateValue `json:"requestedValue,omitempty"`
	// Value undocumented
	Value *DeploymentStateValue `json:"value,omitempty"`
}

// DeploymentStateReason undocumented
type DeploymentStateReason struct {
	// Object is the base model of DeploymentStateReason
	Object
	// Value undocumented
	Value *DeploymentStateReasonValue `json:"value,omitempty"`
}
