// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// ChangeTrackedEntityRequestBuilder is request builder for ChangeTrackedEntity
type ChangeTrackedEntityRequestBuilder struct{ BaseRequestBuilder }

// Request returns ChangeTrackedEntityRequest
func (b *ChangeTrackedEntityRequestBuilder) Request() *ChangeTrackedEntityRequest {
	return &ChangeTrackedEntityRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ChangeTrackedEntityRequest is request for ChangeTrackedEntity
type ChangeTrackedEntityRequest struct{ BaseRequest }

// Get performs GET request for ChangeTrackedEntity
func (r *ChangeTrackedEntityRequest) Get(ctx context.Context) (resObj *ChangeTrackedEntity, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ChangeTrackedEntity
func (r *ChangeTrackedEntityRequest) Update(ctx context.Context, reqObj *ChangeTrackedEntity) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ChangeTrackedEntity
func (r *ChangeTrackedEntityRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
