// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// AddToReviewSetOperationRequestBuilder is request builder for AddToReviewSetOperation
type AddToReviewSetOperationRequestBuilder struct{ BaseRequestBuilder }

// Request returns AddToReviewSetOperationRequest
func (b *AddToReviewSetOperationRequestBuilder) Request() *AddToReviewSetOperationRequest {
	return &AddToReviewSetOperationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// AddToReviewSetOperationRequest is request for AddToReviewSetOperation
type AddToReviewSetOperationRequest struct{ BaseRequest }

// Get performs GET request for AddToReviewSetOperation
func (r *AddToReviewSetOperationRequest) Get(ctx context.Context) (resObj *AddToReviewSetOperation, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for AddToReviewSetOperation
func (r *AddToReviewSetOperationRequest) Update(ctx context.Context, reqObj *AddToReviewSetOperation) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for AddToReviewSetOperation
func (r *AddToReviewSetOperationRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
