// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// NoncustodialDataSourceRequestBuilder is request builder for NoncustodialDataSource
type NoncustodialDataSourceRequestBuilder struct{ BaseRequestBuilder }

// Request returns NoncustodialDataSourceRequest
func (b *NoncustodialDataSourceRequestBuilder) Request() *NoncustodialDataSourceRequest {
	return &NoncustodialDataSourceRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// NoncustodialDataSourceRequest is request for NoncustodialDataSource
type NoncustodialDataSourceRequest struct{ BaseRequest }

// Get performs GET request for NoncustodialDataSource
func (r *NoncustodialDataSourceRequest) Get(ctx context.Context) (resObj *NoncustodialDataSource, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for NoncustodialDataSource
func (r *NoncustodialDataSourceRequest) Update(ctx context.Context, reqObj *NoncustodialDataSource) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for NoncustodialDataSource
func (r *NoncustodialDataSourceRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
