// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// TermStorestoreRequestBuilder is request builder for TermStorestore
type TermStorestoreRequestBuilder struct{ BaseRequestBuilder }

// Request returns TermStorestoreRequest
func (b *TermStorestoreRequestBuilder) Request() *TermStorestoreRequest {
	return &TermStorestoreRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// TermStorestoreRequest is request for TermStorestore
type TermStorestoreRequest struct{ BaseRequest }

// Get performs GET request for TermStorestore
func (r *TermStorestoreRequest) Get(ctx context.Context) (resObj *TermStorestore, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for TermStorestore
func (r *TermStorestoreRequest) Update(ctx context.Context, reqObj *TermStorestore) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for TermStorestore
func (r *TermStorestoreRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
