// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// EdiscoveryrootRequestBuilder is request builder for Ediscoveryroot
type EdiscoveryrootRequestBuilder struct{ BaseRequestBuilder }

// Request returns EdiscoveryrootRequest
func (b *EdiscoveryrootRequestBuilder) Request() *EdiscoveryrootRequest {
	return &EdiscoveryrootRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// EdiscoveryrootRequest is request for Ediscoveryroot
type EdiscoveryrootRequest struct{ BaseRequest }

// Get performs GET request for Ediscoveryroot
func (r *EdiscoveryrootRequest) Get(ctx context.Context) (resObj *Ediscoveryroot, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for Ediscoveryroot
func (r *EdiscoveryrootRequest) Update(ctx context.Context, reqObj *Ediscoveryroot) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for Ediscoveryroot
func (r *EdiscoveryrootRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
